name: Main

on: [push]

jobs:

  build:
    env: 
      AOC_USER: blacha
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    # Configure the .aocrc to look at .aoc-data
    - name: .aocrc
      run: echo "AOC_DATA_PATH=$GITHUB_WORKSPACE" > $GITHUB_WORKSPACE/.aocrc

    - name: Install
      run: yarn install

    - name: Lint
      run: yarn run lint

    - name: Build
      run: yarn run build

    - name: Test
      run: yarn run test
